# Generated by Django 4.2 on 2023-04-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
